//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualJsonEditor.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualJsonEditor.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Remove.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string ButtonSaveAs {
            get {
                return ResourceManager.GetString("ButtonSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Schema As.
        /// </summary>
        public static string ButtonSaveSchemaAs {
            get {
                return ResourceManager.GetString("ButtonSaveSchemaAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ButtonValidate {
            get {
                return ResourceManager.GetString("ButtonValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files (*.json)|*.json|All files (*.*)|*.*.
        /// </summary>
        public static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Visual JSON Editor.
        /// </summary>
        public static string HeaderAboutWindow {
            get {
                return ResourceManager.GetString("HeaderAboutWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual JSON Editor.
        /// </summary>
        public static string HeaderMainWindow {
            get {
                return ResourceManager.GetString("HeaderMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Documents.
        /// </summary>
        public static string HeaderRecentDocuments {
            get {
                return ResourceManager.GetString("HeaderRecentDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual JSON Editor has been developed by .
        /// </summary>
        public static string LabelAbout1 {
            get {
                return ResourceManager.GetString("LabelAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking windows control for WPF. .
        /// </summary>
        public static string LabelAboutComponentAvalonDock {
            get {
                return ResourceManager.GetString("LabelAboutComponentAvalonDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library with ribbon UI implementation. .
        /// </summary>
        public static string LabelAboutComponentFluentRibbon {
            get {
                return ResourceManager.GetString("LabelAboutComponentFluentRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular high-performance JSON framework for .NET..
        /// </summary>
        public static string LabelAboutComponentJsonNet {
            get {
                return ResourceManager.GetString("LabelAboutComponentJsonNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET library with MVVM classes, controls and more components..
        /// </summary>
        public static string LabelAboutComponentMyToolkit {
            get {
                return ResourceManager.GetString("LabelAboutComponentMyToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Schema draft v4 reader and generator for .NET.
        /// </summary>
        public static string LabelAboutComponentNJsonSchema {
            get {
                return ResourceManager.GetString("LabelAboutComponentNJsonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string LabelAboutComponents {
            get {
                return ResourceManager.GetString("LabelAboutComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls library..
        /// </summary>
        public static string LabelAboutComponentWpfToolkit {
            get {
                return ResourceManager.GetString("LabelAboutComponentWpfToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (read-only).
        /// </summary>
        public static string LabelReadOnly {
            get {
                return ResourceManager.GetString("LabelReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string MessageErrorText {
            get {
                return ResourceManager.GetString("MessageErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string MessageErrorTitle {
            get {
                return ResourceManager.GetString("MessageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is NOT valid. 
        ///
        ///{1}.
        /// </summary>
        public static string MessageNotValidDocumentText {
            get {
                return ResourceManager.GetString("MessageNotValidDocumentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid document.
        /// </summary>
        public static string MessageNotValidDocumentTitle {
            get {
                return ResourceManager.GetString("MessageNotValidDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document &apos;{0}&apos;?.
        /// </summary>
        public static string MessageSaveDocumentText {
            get {
                return ResourceManager.GetString("MessageSaveDocumentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save document.
        /// </summary>
        public static string MessageSaveDocumentTitle {
            get {
                return ResourceManager.GetString("MessageSaveDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is valid. .
        /// </summary>
        public static string MessageValidDocumentText {
            get {
                return ResourceManager.GetString("MessageValidDocumentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid document.
        /// </summary>
        public static string MessageValidDocumentTitle {
            get {
                return ResourceManager.GetString("MessageValidDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open JSON document.
        /// </summary>
        public static string OpenJsonDocumentDialog {
            get {
                return ResourceManager.GetString("OpenJsonDocumentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select JSON schema document.
        /// </summary>
        public static string OpenJsonSchemaDocumentDialog {
            get {
                return ResourceManager.GetString("OpenJsonSchemaDocumentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string RibbonGroupFile {
            get {
                return ResourceManager.GetString("RibbonGroupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string RibbonGroupMore {
            get {
                return ResourceManager.GetString("RibbonGroupMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl-N.
        /// </summary>
        public static string ShortcutCtrlN {
            get {
                return ResourceManager.GetString("ShortcutCtrlN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl-O.
        /// </summary>
        public static string ShortcutCtrlO {
            get {
                return ResourceManager.GetString("ShortcutCtrlO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl-S.
        /// </summary>
        public static string ShortcutCtrlS {
            get {
                return ResourceManager.GetString("ShortcutCtrlS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl-U.
        /// </summary>
        public static string ShortcutCtrlU {
            get {
                return ResourceManager.GetString("ShortcutCtrlU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl-W.
        /// </summary>
        public static string ShortcutCtrlW {
            get {
                return ResourceManager.GetString("ShortcutCtrlW", resourceCulture);
            }
        }
    }
}
